### ISSUE TITLE
Research Article PDF

### ISSUE THREAD

**Issue by SahilSingh177** [vinit714/A-Recommendation-system-for-Facial-Skin-Care-using-Machine-Learning-Models#1]
I reviewed the repo and I'm very interested in the research article you published. Could you please share it? IEEE requires institutional access, which I currently don't have.

**Comment by vinit714** [comment]
Sure, please find the research article attached.
[Efficient_Net-based_Expert_System_for_Personalized_Facial_Skincare_Recommendations (3).pdf](https://github.com/vinit714/A-Recommendation-system-for-Facial-Skin-Care-using-Machine-Learning-Models/files/15316507/Efficient_Net-based_Expert_System_for_Personalized_Facial_Skincare_Recommendations.3.pdf)

**Comment by vinit714** [comment]
> I reviewed the repo and I'm very interested in the research article you published. Could you please share it? IEEE requires institutional access, which I currently don't have.

Sure, please find the research article attached
[Uploading Efficient_Net-based_Expert_System_for_Personalized_Facial_Skincare_Recommendations.3.pdf…]()

**Comment by vinit714** [comment]
> I reviewed the repo and I'm very interested in the research article you published. Could you please share it? IEEE requires institutional access, which I currently don't have.

Sure, please find the research article attached
[Efficient_Net-based_Expert_System_for_Personalized_Facial_Skincare_Recommendations.3.pdf](https://github.com/vinit714/A-Recommendation-system-for-Facial-Skin-Care-using-Machine-Learning-Models/files/15316572/Efficient_Net-based_Expert_System_for_Personalized_Facial_Skincare_Recommendations.3.pdf)
